version: "3.8"

services:
  dashboard-coinzone:
    image: dashboard-coinzone
    container_name: dashboard-coinzone
    build: .
    ports:
      - "3001:9001"
    environment:
      - NODE_ENV=production
    restart: always
