version: '3.8'

services:
  portal-web:
    build: .
    container_name: portal-web
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: ["npm", "start"]
    environment:
      - NODE_ENV=production
